version: "3.8"
services:
  web:
    container_name: backend
    build:
      context: ./
      target: dev
    volumes:
      - .:/src
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*
      WAIT_HOSTS: kraftfahrzeugdb:27017
  kraftfahrzeugdb:
    image: mongo
    container_name: kraftfahrzeug
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ~/mongodb/kraftfahrzeugdb:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
